.gitattributes
.gitignore
.mailmap

Add .gitattributes file
Add .mailmap file
Update .gitignore file

Add .gitattributes, .mailmap Update .gitignore file

---

.gitignore
git-hooks/add-hooks
git-hooks/pre-commit

- fix pre-commit hook to stop commit if projec build fail
- add scrip temorary files to gitignore again
- add message to add-hooks script

Closes: #6

---

src/main/java/edition/academy/seventh/Main.java
src/main/java/edition/academy/seventh/controller/BookController.java
src/main/java/edition/academy/seventh/database/connector/PostgresConnector.java
src/main/java/edition/academy/seventh/repository/BookRepository.java
src/main/java/edition/academy/seventh/serivce/BooksService.java

- add one enpoind that returns list of books
- add method to book service and repository to handle getting books from
database

Closes: #58

---

src/main/java/edition/academy/seventh/Main.java
src/main/java/edition/academy/seventh/controller/BookController.java
src/main/java/edition/academy/seventh/repository/BookRepository.java
src/main/java/edition/academy/seventh/serivce/BookService.java

- close connection to database from controller
- ResponseEntity<List<Book>>
-refactor name BookService

Sprint#1, Task#63, close connection to database

---

git-hooks/add-hooks

- change language of a message from Polish to English
- add a message about completion of script execution

Closes: #75

---

pom.xml
src/main/java/edition/academy/seventh/Main.java
src/main/java/edition/academy/seventh/controller/BookController.java
src/main/java/edition/academy/seventh/database/connector/EntityConnector.java
src/main/java/edition/academy/seventh/repository/BookRepository.java
src/main/java/edition/academy/seventh/serivce/BookDataDownloader.java
src/main/java/edition/academy/seventh/serivce/BookService.java
src/main/java/edition/academy/seventh/serivce/EmpikScrapper.java
src/main/java/edition/academy/seventh/serivce/ItBookMapper.java
src/main/java/edition/academy/seventh/serivce/ItbookBookstoreConnectionService.java
src/main/java/edition/academy/seventh/serivce/JsonDataProcessor.java
src/main/java/edition/academy/seventh/serivce/PromotionProvider.java
src/main/resources/META-INF/persistence.xml
src/test-integration/java/edition/academy/seventh/serivce/BookstoreConnectorTestIT.java
src/test-integration/java/edition/academy/seventh/serivce/DataProviderForJsonParser.java
src/test-integration/java/edition/academy/seventh/serivce/EmpikScrapperTestIT.java
src/test/java/edition/academy/seventh/serivce/BookDataDownloaderTest.java
src/test/java/edition/academy/seventh/serivce/BookMapperTest.java
src/test/java/edition/academy/seventh/serivce/BookServiceTest.java

Fix all issue foud by reviewers in "Sprint#2 Wednesday merge develop to master" pull request

Closes: #105

---

src/main/java/edition/academy/seventh/service/EmpikScrapper.java

Add appropriate error logs when exception occurs
Add info logs when scrapping task is submitted 
Adjust java docs, methods & variables names

110#dodanie logowania

---

check_environment_variables_script.sh
src/main/java/edition/academy/seventh/controller/RobotController.java

- Dodanie skryptu check_environment_variables_script.sh, który sprawdza zmienne środowiskowe
- Implementacja odpalania skryptu w klasie RobotController

Closes #80

---

src/main/java/edition/academy/seventh/controller/RobotController.java
src/main/java/edition/academy/seventh/database/connector/H2Connector.java
src/main/java/edition/academy/seventh/repository/BookRepository.java
src/main/java/edition/academy/seventh/service/BookDataDownloader.java
src/main/java/edition/academy/seventh/service/mapper/ItBookMapper.java
src/main/java/edition/academy/seventh/service/scrapper/AbstractScrapper.java

Add loggers
Add logged messages
Improve some javadocs
fix few typoos

Closes #110

---

src/main/java/edition/academy/seventh/database/connector/ConnectorProvider.java
src/main/java/edition/academy/seventh/database/connector/EntityConnector.java
src/main/java/edition/academy/seventh/repository/BookRepository.java

- dodanie metody close() do API ConnectorProvider
- refaktoryzacja klasy EntityConnector
- dodanie dokumentacji
- refaktoryzacja zamykania menadżera encji na wywołanie metody connectionProvider.close()

Closes: #135

---

src/main/java/edition/academy/seventh/Main.java
src/main/java/edition/academy/seventh/service/scrapper/BookoffScrapper.java
src/main/java/edition/academy/seventh/service/scrapper/ScrapperConfiguration.java
src/test/java/edition/academy/seventh/service/scrapper/BookoffScrapperTestIT.java

- Implementacja zdrapywania księgarni bookoff.pl
- Test integracyjne potwierdzające poprawność działania powyższej klasy

Closes: #176

---

src/main/java/edition/academy/seventh/service/scrapper/RaveloScrapper.java
src/main/java/edition/academy/seventh/service/scrapper/ScrapperConfiguration.java
src/test/java/edition/academy/seventh/service/scrapper/RaveloScrapperTestIT.java

Dodaje możliwość zdrapywania kolejnej księgarni - Ravelo.pl
- Implementacja zdrapywania stron ravelo.pl
- Napisanie testu sprawdzającego poprawność implementacji

Closes: #181

---

src/main/java/edition/academy/seventh/service/scrapper/EmpikScrapper.java
src/main/java/edition/academy/seventh/service/scrapper/TaniaKsiazkaScrapper.java

- Zamiana ceny detalicznej i promocyjnej w zdrapywaniu z empiku
- Zamiana linku z obrazem w zdrapywaniu TaniejKsiązki
- Usunięcie metody usuwającej walutę z ceny

Closes: #204

---

src/main/java/edition/academy/seventh/display/EagerBookPagination.java
src/test/java/edition/academy/seventh/display/EagerBookPaginationTest.java

Sprint#3, Task#197 bugfix

---

src/main/java/edition/academy/seventh/controller/BookController.java

Sprint#3, usuwa dodawanie 'www'

---

src/main/java/edition/academy/seventh/connector/EntityConnector.java
src/main/java/edition/academy/seventh/connector/H2Connector.java
src/main/java/edition/academy/seventh/pagination/BookFilterType.java
src/main/java/edition/academy/seventh/pagination/EagerBookPagination.java
src/main/java/edition/academy/seventh/pagination/LazyBookPaginationRepositoryHandler.java
src/main/java/edition/academy/seventh/pagination/PaginationController.java
src/main/java/edition/academy/seventh/pagination/PaginationFactory.java
src/main/java/edition/academy/seventh/persistence/BookRepository.java
src/main/java/edition/academy/seventh/scrapping/RobotScrappingStarter.java
src/main/java/edition/academy/seventh/security/AuthenticationRestController.java
src/main/java/edition/academy/seventh/security/AuthenticationService.java
src/main/java/edition/academy/seventh/security/DatabaseInitializer.java
src/main/java/edition/academy/seventh/security/RoleRepository.java
src/main/java/edition/academy/seventh/security/UserDetailsServiceImpl.java
src/main/java/edition/academy/seventh/security/UserPrinciple.java
src/main/java/edition/academy/seventh/security/UserRepository.java
src/main/java/edition/academy/seventh/security/WebSecurityConfig.java
src/main/java/edition/academy/seventh/security/model/RoleName.java
src/main/java/edition/academy/seventh/security/model/User.java
src/main/java/edition/academy/seventh/security/request/LoginForm.java
src/main/java/edition/academy/seventh/security/response/JwtResponse.java
src/main/java/edition/academy/seventh/security/response/ResponseMessage.java
src/main/resources/application.properties
src/test/java/edition/academy/seventh/persistence/BookRepositoryTestIT.java
src/test/java/edition/academy/seventh/security/AuthenticationRestControllerTestIT.java
src/test/java/edition/academy/seventh/security/AuthenticationServiceTest.java
src/test/java/edition/academy/seventh/security/AuthenticationServiceTestIT.java
src/test/java/edition/academy/seventh/security/RepositoryTestIT.java
src/test/resources/test.properties

Sprint#5 Task#248 Dodanie testów JWT oraz poprawa inicjalizacji bazy danych
-inicjalizacja danych poprzez plik z właściwościami
-usunięcie zamykania połączenia
-zamykanie entityManagera
-testy integracyjne autentykacja

Closes #248

---

src/main/java/edition/academy/seventh/pagination/PaginationController.java
src/main/java/edition/academy/seventh/persistence/BookRetriever.java
src/main/java/edition/academy/seventh/scrapping/RobotScrappingStarter.java
src/main/java/edition/academy/seventh/security/AuthenticationRestController.java
src/main/resources/application.properties
src/test/resources/test.properties

Closes #254

---

src/test/java/edition/academy/seventh/scrapping/RobotScrappingStarterTestIT.java
src/test/java/edition/academy/seventh/security/AuthenticationRestControllerTestIT.java

-dodanie testów Cors do RobotScrappingStarterTestIT i AuthenticationRestContrellerTestIT

Closes: #277

---

pom.xml
src/test/java/edition/academy/seventh/AppSmokeTest.java
src/test/java/edition/academy/seventh/SmokeTest.java
src/test/java/edition/academy/seventh/pagination/PaginationControllerSmokeTest.java
src/test/java/edition/academy/seventh/persistence/BookRetrieverSmokeTest.java
src/test/java/edition/academy/seventh/scrapping/RobotScrappingStarterSmokeTest.java
src/test/java/edition/academy/seventh/security/AuthenticationRestControllerSmokeTest.java

Closes: #283

---

src/main/java/edition/academy/seventh/security/AuthenticationRestController.java
src/main/java/edition/academy/seventh/security/request/RegisterForm.java
src/test/java/edition/academy/seventh/security/AuthenticationRestControllerTestIT.java

Po moich zmianach system działa następująco:
Rejestrowanie użytkownika poprzez formularz -> domyślnie z rolą użykownika
Dodatkowa końcówka (/newUser) rejestrująca użytkownika z dowolnymi uprawnieniami - dostepna wyłącznie dla istniejących już administratorów

Closes: 289

---

src/main/java/edition/academy/seventh/persistence/BookDtoParser.java
src/main/java/edition/academy/seventh/persistence/BookRepository.java
src/main/java/edition/academy/seventh/persistence/BookRetriever.java
src/main/java/edition/academy/seventh/persistence/BookService.java
src/main/java/edition/academy/seventh/persistence/ModelParserIntoBookDtos.java
src/main/java/edition/academy/seventh/persistence/model/BookstoreBook.java
src/main/java/edition/academy/seventh/persistence/response/BookDto.java
src/main/java/edition/academy/seventh/persistence/response/BookstoreBookDto.java
src/main/java/edition/academy/seventh/scrapping/BookoffScrapper.java
src/main/java/edition/academy/seventh/scrapping/EmpikScrapper.java
src/main/java/edition/academy/seventh/scrapping/PwnScrapper.java
src/main/java/edition/academy/seventh/scrapping/RaveloScrapper.java
src/main/java/edition/academy/seventh/scrapping/SwiatKsiazkiScrapper.java
src/main/java/edition/academy/seventh/scrapping/TaniaKsiazkaScrapper.java
src/main/java/edition/academy/seventh/security/response/JwtResponse.java
src/test/java/edition/academy/seventh/persistence/BookRepositoryTestIT.java
src/test/java/edition/academy/seventh/persistence/ModelParserIntoBookDtosTest.java

Po zmianach:
1. BookstoreBook ma nowy klucz główny Long id
2. BookDto ma nowe pole id
3. Możliwość usunięcia klasy foo ze względu na usunięcie błędu w zabezpieczniach ( href w get mappingu ===> teraz long w mappingu /bookUrl/{id} )

Closes#253

---

src/main/java/edition/academy/seventh/security/WebSecurityConfig.java

Usunięcie klasy foo oraz jej wykorzystania

Closes #297

---

src/main/java/edition/academy/seventh/security/AuthenticationRestController.java
src/main/java/edition/academy/seventh/security/AuthenticationService.java

-zmiany w logowaniu w klasach AuthenticationRestController i AthenticationService na logowanie jedynie nazwy użytkownika

Closes: #264
